import pool from '../config/db.js';

// GET /patients?page=&limit=&search= — search matches full_name, nik, AND
// patient_number so a barcode scan (which types patient_number into the
// search input) finds the patient immediately.
async function list(req, res) {
  const page = Math.max(parseInt(req.query.page, 10) || 1, 1);
  const limit = Math.min(parseInt(req.query.limit, 10) || 20, 100);
  const search = req.query.search ? `%${req.query.search}%` : null;
  const offset = (page - 1) * limit;

  const whereClause = search ? 'WHERE full_name ILIKE $1 OR nik ILIKE $1 OR patient_number ILIKE $1' : '';
  const params = search ? [search] : [];

  const { rows: countRows } = await pool.query(
    `SELECT COUNT(*)::int AS total FROM patients ${whereClause}`,
    params
  );
  const totalItems = countRows[0].total;

  const { rows } = await pool.query(
    `SELECT id, patient_number, full_name, nik, dob, phone, email, address, allergies, created_at
     FROM patients
     ${whereClause}
     ORDER BY created_at DESC
     LIMIT $${params.length + 1} OFFSET $${params.length + 2}`,
    [...params, limit, offset]
  );

  res.json({
    data: rows,
    pagination: {
      page,
      limit,
      total_items: totalItems,
      total_pages: Math.ceil(totalItems / limit),
    },
  });
}

// GET /patients/:id — patient detail plus their medical record history.
async function getById(req, res) {
  const { id } = req.params;

  const { rows: patientRows } = await pool.query('SELECT * FROM patients WHERE id = $1', [id]);
  const patient = patientRows[0];

  if (!patient) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Patient not found' } });
  }

  const { rows: medicalRecords } = await pool.query(
    `SELECT mr.id, mr.complaint, mr.diagnosis, mr.notes, mr.created_at, u.full_name AS doctor_name,
            i.total_amount AS invoice_total, i.status AS invoice_status
     FROM medical_records mr
     LEFT JOIN users u ON u.id = mr.doctor_id
     LEFT JOIN invoices i ON i.medical_record_id = mr.id
     WHERE mr.patient_id = $1
     ORDER BY mr.created_at DESC`,
    [id]
  );

  res.json({ data: { ...patient, medical_records: medicalRecords } });
}

// GET /patients/:id/medical-records?from=&to= — full-history document for
// printing (06-design-system.md "Cetak Rekam Medis"), not a list endpoint —
// no pagination, since the point is one complete printable document.
async function getMedicalRecordsForPrint(req, res) {
  const { id } = req.params;
  const { from, to } = req.query;

  const { rows: patientRows } = await pool.query(
    'SELECT full_name, patient_number, dob, nik, address FROM patients WHERE id = $1',
    [id]
  );
  const patient = patientRows[0];

  if (!patient) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Patient not found' } });
  }

  const { rows: records } = await pool.query(
    `SELECT mr.id, mr.created_at::date AS visit_date, mr.complaint, mr.diagnosis, mr.notes, u.full_name AS doctor_name
     FROM medical_records mr
     LEFT JOIN users u ON u.id = mr.doctor_id
     WHERE mr.patient_id = $1
       AND ($2::date IS NULL OR mr.created_at::date >= $2::date)
       AND ($3::date IS NULL OR mr.created_at::date <= $3::date)
     ORDER BY mr.created_at ASC`,
    [id, from || null, to || null]
  );

  for (const record of records) {
    const { rows: items } = await pool.query(
      `SELECT m.name AS medicine_name, pi.dosage, pi.quantity
       FROM prescription_items pi
       JOIN prescriptions p ON p.id = pi.prescription_id
       JOIN medicines m ON m.id = pi.medicine_id
       WHERE p.medical_record_id = $1
       ORDER BY pi.created_at ASC`,
      [record.id]
    );
    record.prescription_items = items;
    delete record.id;
  }

  res.json({ patient, records });
}

// POST /patients — patient_number is generated by the database default, never sent by the client.
async function create(req, res) {
  const { full_name, nik, dob, phone, email, address, village, district, city, province, postal_code, allergies } = req.body;

  if (!full_name) {
    return res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'full_name is required' } });
  }

  const { rows } = await pool.query(
    `INSERT INTO patients (full_name, nik, dob, phone, email, address, village, district, city, province, postal_code, allergies)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
     RETURNING *`,
    [
      full_name,
      nik || null,
      dob || null,
      phone || null,
      email || null,
      address || null,
      village || null,
      district || null,
      city || null,
      province || null,
      postal_code || null,
      allergies || null,
    ]
  );

  res.status(201).json({ data: rows[0] });
}

async function update(req, res) {
  const { id } = req.params;
  const { full_name, nik, dob, phone, email, address, village, district, city, province, postal_code, allergies } = req.body;

  const { rows } = await pool.query(
    `UPDATE patients
     SET full_name = COALESCE($1, full_name),
         nik = COALESCE($2, nik),
         dob = COALESCE($3, dob),
         phone = COALESCE($4, phone),
         email = COALESCE($5, email),
         address = COALESCE($6, address),
         village = COALESCE($7, village),
         district = COALESCE($8, district),
         city = COALESCE($9, city),
         province = COALESCE($10, province),
         postal_code = COALESCE($11, postal_code),
         allergies = COALESCE($12, allergies)
     WHERE id = $13
     RETURNING *`,
    [
      full_name ?? null,
      nik ?? null,
      dob ?? null,
      phone ?? null,
      email ?? null,
      address ?? null,
      village ?? null,
      district ?? null,
      city ?? null,
      province ?? null,
      postal_code ?? null,
      allergies ?? null,
      id,
    ]
  );

  if (!rows[0]) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Patient not found' } });
  }

  res.json({ data: rows[0] });
}

export default { list, getById, create, update, getMedicalRecordsForPrint };
